### ISSUE TITLE
Custom `title` property in SMW query UL output

### ISSUE THREAD

**Issue by lucamauri** [SemanticMediaWiki/SemanticMediaWiki#5253]
In my wiki, I use a CSS fragment to automatically create a title string by formatting the `title` property of a `<ul>` tag:
```css
.exampleclass ul[title]::before {
    content: attr(title);
    display: block;
    font-weight: bold;
    margin-top: 7px;
    margin-bottom: 5px;
}
```
Unfortunately I can't use this functionality with the results of SMW queries because, when I set `|format=ul` as output, I can only set the CSS class `|class=exampleclass` and no more HTML properties.

I suggest to add an option to query parameters, `name`, to allow adding this property to the tag. Furthermore, it might be beneficial to create a more generic `attributes` parameter to allow the injection of arbitrary attributes to the HTML tag (be it `<ul>` or `<ol>` or whatever).
